version: "3"

services:
  php-apache:
    container_name: "symfony-assessment-apache-php"
    build: ./docker/php-apache
    volumes:
      - ./sf6:/var/www/html
    ports:
      - 80:80

  db:
    container_name: "symfony-assessment-mariadb"
    env_file:
      - .env
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_USER=${ROOT_USER}
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
    volumes:
      - db:/var/lib/mysql:rw
    ports:
      - 3306:3306

  adminer:
    container_name: "symfony-assessment-adminer"
    image: adminer
    ports:
      - 8080:8080

volumes:
  php-apache:
  db: