controllers:
    resource:
        path: ../src/Infra/Controller/
        namespace: App\Infra\Controller
    type: attribute
    prefix: '/api/v1'
kernel:
    resource: App\Kernel
    type: attribute