name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  static-analysis-and-coding-standards:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: sqlite3
          tools: composer:v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run Psalm
        run: vendor/bin/psalm

      - name: Run PHP_CodeSniffer
        run: vendor/bin/phpcs --standard=PSR12 src/

      - name: Run PHPUnit tests
        run: php bin/phpunit
